version: "3"

volumes:
   pow-embed-shared:

services:
  textile:
    build: .
    environment:
      - TXTL_ADDR_API=/ip4/0.0.0.0/tcp/3006
      - TXTL_ADDR_API_PROXY=/ip4/0.0.0.0/tcp/3007
      - TXTL_ADDR_THREADS_HOST=/ip4/0.0.0.0/tcp/4006
      - TXTL_ADDR_GATEWAY_HOST=/ip4/0.0.0.0/tcp/8006
      - TXTL_ADDR_MONGO_URI=mongodb://mongo:27017
      - TXTL_ADDR_IPFS_API=/dns4/ipfs/tcp/5001
      - TXTL_EMAIL_SESSION_SECRET=textilesession
      - TXTL_ADDR_POWERGATE_API=/dns4/pow/tcp/5011
    ports:
      - "127.0.0.1:3006:3006"
      - "3007:3007"
      - "4006:4006"
      - "127.0.0.1:8006:8006"

  powergate:
    image: textile/powergate:sha-a4f401e
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - ipfsbuckets
      - lotus
    environment:
      - POWD_EMBEDDED=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    volumes:
      - pow-embed-shared:/tmp/powergate
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.5.1

  ipfsbuckets:
    image: ipfs/go-ipfs:v0.5.1
    ports:
      - 5011:5001

  mongo:
    image: mongo:latest
    ports:
      - 27027:27017

  lotus:
    image: textile/lotus-devnet:sha-0853126
    environment:
      - TEXLOTUSDEVNET_SPEED=2000
    volumes:
     - pow-embed-shared:/tmp/powergate
